type Query {
  seasonList: [Season!]!
  raceByYear(year: String!): [Race!]!
  roundByYear(year: String!, round: Int): Race!
  drivers(perPage: Int, page: Int): [Driver!]!
  driversByYear(year: String!): [Driver!]!
  driversByYearAndRound(year: String!, round: Int!): [Driver!]!
  driversById(id: String!): Driver!
  driversStandingsByYear(year: String!): [DriverStanding!]!
  circuits(perPage: Int, page: Int): [Circuit!]!
}

type Season {
  year: String!
  url: String!
  urlMobile: String!
}

type Race {
  season: String!
  round: String!
  url: String!
  name: String!
  circuit: Circuit!
  date: String!
  time: String
  urlMobile: String!
}

type Circuit {
  id: ID!
  url: String!
  name: String!
  location: Location!
  urlMobile: String!
}

type Location {
  lat: String!
  lng: String!
  locality: String!
  country: String!
}

type Driver {
  id: String!
  url: String!
  urlMobile: String!
  name: String!
  dateOfBirth: String!
  nationality: String!
  code: String
  permanentNumber: String
}

type DriverStanding {
  position: String!
  positionText: String!
  points: String!
  wins: String!
  driver: Driver!
  constructors: [Constructor!]!
}

type Constructor {
  id: String!
  url: String!
  urlMobile: String!
  name: String!
  nationality: String!
}
