type Query {
  seasonList: [Season!]!
  raceByYear(year: String!): [Race!]!
  roundByYear(year: String!, round: Int): Race!
}

type Season {
  year: String!
  url: String!
  urlMobile: String!
}

type Race {
  season: String!
  round: String!
  url: String!
  name: String!
  circuit: Circuit!
  date: String!
  time: String
  urlMobile: String!
}

type Circuit {
  id: ID!
  url: String!
  name: String!
  location: Location!
  urlMobile: String!
}

type Location {
  lat: String!
  lng: String!
  locality: String!
  country: String!
}
